// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3iISaV8ijm35QFrfI2mpjSxp9gs0_I3M',
    appId: '1:32337360662:web:9625be99e7521ff410c237',
    messagingSenderId: '32337360662',
    projectId: 'borja-firebase-project',
    authDomain: 'borja-firebase-project.firebaseapp.com',
    storageBucket: 'borja-firebase-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3hR6U56A0u7LmpffviAvDdiHVVllKzlU',
    appId: '1:32337360662:android:224b8c837fb503af10c237',
    messagingSenderId: '32337360662',
    projectId: 'borja-firebase-project',
    storageBucket: 'borja-firebase-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-thrRCFBBxxaUXnHqNCq3vFcT30rDFGA',
    appId: '1:32337360662:ios:2f605ea7f704322d10c237',
    messagingSenderId: '32337360662',
    projectId: 'borja-firebase-project',
    storageBucket: 'borja-firebase-project.appspot.com',
    iosBundleId: 'com.example.stateChangeDemo',
  );
}
